### PR TITLE
Fix bounding box height

### PR DESCRIPTION
**Pull request by CharlesXu1124**
- fix bounding box z position
- fix footprint points z position

### CODE REVIEW

**Review by JWhitleyWork — APPROVED** [review]

**Comment by LawrenceXu13467** [comment]
Unfortunately, the issues persist. There are negative underground bounding boxes. No more 180-degree sudden rotations, but still some significant rotations even on stationary objects.

Screenshot 2023-09-05 10:01:25

**Comment by JWhitleyWork** [comment]
> Unfortunately, the issues persist. There are negative underground bounding boxes. No more 180-degree sudden rotations, but still some significant rotations even on stationary objects.

Bounding boxes extending below the ground is OK as long as the points are correctly surrounded by the bounding boxes. Please verify it with these criteria.

**Comment by LawrenceXu13467** [comment]
> > Unfortunately, the issues persist. There are negative underground bounding boxes. No more 180-degree sudden rotations, but still some significant rotations even on stationary objects.
> 
> Bounding boxes extending below the ground is OK as long as the points are correctly surrounded by the bounding boxes. Please verify it with these criteria.

I took a random frame and see some issues below:

1. The points are there but the box is not surrounding the object, but right below the object (first image below, we can see the car above the white box). Almost all boxes in general have partials below the ground (second image).

Screenshot 2023-09-05 12:37:03



Screenshot 2023-09-05 12:39:30



3. Large boxes towards the center of the road would block the drive-able area in front of the ego vehicle. 



Screenshot 2023-09-05 12:41:38

**Comment by CharlesXu1124** [comment]
for 1, it's caused by the incorrect z value of the minimum point of the bounding box, that should be fixed in https://github.com/upowerrobotics/autoware.universe/pull/10/commits/2e48890869849da00cf879a1c4da7a47aaf3440b
image

**Pull request merged**
