### PR TITLE
Update universe planning

### PR DESCRIPTION
**Pull request by cszeng**
1. Upgrade the planning related packages to the almost latest version of autoware.universe  (i.e. commit f8923b0f0735315fd94c1723bbfa0b5e7184c313) and resolve compilation errors.
 
2.  Add python launch files for packages as follows: mission_planner, planning_evalutator, planning_validator, rtc_auto_mode_manager, ad_api_adaptors, external_velocity_limit_selector, motion_velocity_smoother and scenario_selector.

3. remove unnecessary packages which were used to run the planning simulator.

**Removed packages**: 

**visualization**
rtc_manager_rviz_plugin
bag_time_manager_rviz_plugin
rtc_manager_rviz_plugin
tier4_adapi_rviz_plugin
tier4_automatic_goal_rviz_plugin
tier4_calibration_rviz_plugin
tier4_control_rviz_plugin
tier4_datetime_rviz_plugin
tier4_debug_rviz_plugin
tier4_localization_rviz_plugin
tier4_planning_rviz_plugin
tier4_screen_capture_rviz_plugin
tier4_simulated_clock_rviz_plugin
tier4_state_rviz_plugin
tier4_traffic_light_rviz_plugin
tier4_vehicle_rviz_plugin
tier4_perception_rviz_plugin.

**launch**
tier4_autoware_api_launch
tier4_control_launch
tier4_localization_launch
tier4_map_launch
tier4_perception_launch
tier4_planning_launch
tier4_simulator_launch
tier4_system_launch
tier4_vehicle_launch
polar_grid

**localization**
pose_initializer
ekf_localizer
gyro_odometer
initial_pose_button_panel
localization_error_monitor
pose2twist
stop_filter
twist2accel

**control**
control_performance_analysis
external_cmd_selector
mpc_lateral_controller
obstacle_collision_checker
operation_mode_transition_manager
trajectory_follower_node
pure_pursuit
pid_longitudinal_controller
shift_decider
trajectory_follower_base
vehicle_cmd_gate

**common**
component_interface_tools
path_distance_calculator
tier4_api_utils

**simulator**
simple_planning_simulator
fault_injection

**sensing**
vehicle_velocity_converter

**system**
component_state_monitor
emergency_handler
mrm_comfortable_stop_operator
system_error_monitor
system_monitor

**vehicle**
accel_brake_map_calibrator
external_cmd_converter
raw_vehicle_cmd_converter

### CODE REVIEW

**Comment by CharlesXu1124** [comment]
I would suggest you keep the `autoware_auto_perception_rviz_plugin` and `tier4_perception_rviz_plugin`, as they are used in euclidean cluster package

**Comment by cszeng** [comment]
> I would suggest you keep the `autoware_auto_perception_rviz_plugin` and `tier4_perception_rviz_plugin`, as they are definitely included in euclidean cluster package

no problem. I will bring them back.

**Comment by cszeng** [comment]
> I would suggest you keep the `autoware_auto_perception_rviz_plugin` and `tier4_perception_rviz_plugin`, as they are definitely included in euclidean cluster package

I have restored the two  packages.

**Comment by CharlesXu1124** [comment]
cool, just add to that, you can also remove `tier4_perception_rviz_plugin` as that's for visualization of tier4 messages in rviz2; for `autoware_auto_perception_rviz_plugin` that's not directly used but would be necessary in visualization of `autoware_auto_perception_msgs::msg::DetectedObjects` in rviz2

**Comment by cszeng** [comment]
> cool, just add to that, you can also remove `tier4_perception_rviz_plugin` as that's for visualization of tier4 messages in rviz2; for `autoware_auto_perception_rviz_plugin` that's not directly used but would be necessary in visualization of `autoware_auto_perception_msgs::msg::DetectedObjects` in rviz2

Gotcha. have removed `tier4_perception_rviz_plugin`.

**Comment by JWhitleyWork** [comment]
Thank you for working on this! I assume you have compiled everything and it compiles without error on Galactic? Also, for future pull requests, please split them into individual PRs per feature. A single PR with 1800+ changed files is not feasible for anyone to review.

**Comment by cszeng** [comment]
> Thank you for working on this! I assume you have compiled everything and it compiles without error on Galactic? Also, for future pull requests, please split them into individual PRs per feature. A single PR with 1800+ changed files is not feasible for anyone to review.

Yes. But I forgot to run colcon test. I believe that is alos a must.  I will run colcon test and see if there is any error I need to fix.  And thank you for the reminder.

**Pull request merged**
